/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './src/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "var(--border)",
        input: "var(--input)",
        ring: "var(--ring)",
        background: "var(--background)",
        foreground: "var(--foreground)",
        primary: {
          DEFAULT: "var(--primary)",
          foreground: "var(--primary-foreground)",
        },
        secondary: {
          DEFAULT: "var(--secondary)",
          foreground: "var(--secondary-foreground)",
        },
        destructive: {
          DEFAULT: "var(--destructive)",
          foreground: "var(--destructive-foreground)",
        },
        muted: {
          DEFAULT: "var(--muted)",
          foreground: "var(--muted-foreground)",
        },
        accent: {
          DEFAULT: "var(--accent)",
          foreground: "var(--accent-foreground)",
        },
        popover: {
          DEFAULT: "var(--popover)",
          foreground: "var(--popover-foreground)",
        },
        card: {
          DEFAULT: "var(--card)",
          foreground: "var(--card-foreground)",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      fontFamily: {
        sans: ["var(--font-sans)", "ui-sans-serif", "system-ui", "sans-serif"],
      },
      keyframes: {
        'fade-up': {
          '0%': { opacity: '0', transform: 'translateY(10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'fade-down': {
          '0%': { opacity: '1', transform: 'translateY(0)' },
          '100%': { opacity: '0', transform: 'translateY(10px)' },
        },
        'scale-fade': {
          '0%': { opacity: '1', transform: 'scale(1)' },
          '100%': { opacity: '0', transform: 'scale(0.95)' },
        },
        'logo-reveal': {
          '0%': { opacity: '0', transform: 'scale(1.1)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        }
      },
      animation: {
        'fade-up': 'fade-up 0.5s ease-out forwards',
        'fade-down': 'fade-down 0.5s ease-out forwards',
        'scale-fade': 'scale-fade 0.5s ease-out forwards',
        'logo-reveal': 'logo-reveal 0.6s ease-out forwards',
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
  safelist: [
    'bg-blue-50',
    'bg-blue-100',
    'bg-green-50',
    'bg-green-100',
    'bg-red-50',
    'bg-red-100',
    'bg-yellow-50',
    'bg-gray-50',
    'bg-gray-100',
    'text-blue-600',
    'text-blue-800',
    'text-green-800',
    'text-red-800',
    'text-gray-900',
    'text-gray-600',
    'text-gray-500',
    'rounded-lg',
    'rounded-md',
    'rounded-full',
    'shadow-sm',
    'shadow-xl',
    'border',
    'border-gray-100',
    'border-gray-200',
    'border-gray-300',
    'p-2',
    'p-4',
    'p-6',
    'p-8',
    'px-3',
    'px-4',
    'px-6',
    'py-2',
    'py-4',
    'py-6',
    'py-8',
    'py-12',
    'py-16',
    'py-24',
    'mt-2',
    'mt-4',
    'mt-6',
    'mt-8',
    'mb-2',
    'mb-4',
    'mb-6',
    'mb-8',
    'mx-auto',
    'my-auto',
    'space-y-2',
    'space-y-4',
    'space-x-4',
    'space-x-8',
    'gap-4',
    'gap-6',
    'gap-8',
    'grid',
    'grid-cols-1',
    'grid-cols-2',
    'grid-cols-3',
    'md:grid-cols-2',
    'flex',
    'flex-col',
    'flex-row',
    'items-center',
    'justify-center',
    'justify-between',
    'w-full',
    'h-full',
    'min-h-screen',
    'max-w-full',
    'max-w-4xl',
    'max-w-7xl',
    'relative',
    'absolute',
    'z-10',
    'z-40',
    'z-50',
    'inset-0',
    'top-0',
    'left-0',
    'right-0',
    'bottom-0',
    'overflow-hidden',
    'text-center',
    'text-sm',
    'text-lg',
    'text-xl',
    'text-3xl',
    'text-4xl',
    'font-medium',
    'font-semibold',
    'font-bold',
    'hidden',
    'md:flex',
    'md:w-1/2',
    'lg:flex',
    'lg:flex-1',
    'lg:justify-end',
    'lg:gap-x-12',
    'lg:hidden',
  ],
} 