/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "var(--border)",
        input: "var(--input)",
        ring: "var(--ring)",
        background: "var(--background)",
        foreground: "var(--foreground)",
        primary: {
          50: 'var(--color-primary-50)',
          100: 'var(--color-primary-100)',
          200: 'var(--color-primary-200)',
          300: 'var(--color-primary-300)',
          400: 'var(--color-primary-400)',
          500: 'var(--color-primary-500)',
          600: 'var(--color-primary-600)',
          700: 'var(--color-primary-700)',
          800: 'var(--color-primary-800)',
          900: 'var(--color-primary-900)',
        },
        secondary: {
          50: 'var(--color-secondary-50)',
          100: 'var(--color-secondary-100)',
          200: 'var(--color-secondary-200)',
          300: 'var(--color-secondary-300)',
          400: 'var(--color-secondary-400)',
          500: 'var(--color-secondary-500)',
          600: 'var(--color-secondary-600)',
          700: 'var(--color-secondary-700)',
          800: 'var(--color-secondary-800)',
          900: 'var(--color-secondary-900)',
        },
        success: {
          DEFAULT: 'var(--color-success)',
        },
        warning: {
          DEFAULT: 'var(--color-warning)',
        },
        error: {
          DEFAULT: 'var(--color-error)',
        },
        info: {
          DEFAULT: 'var(--color-info)',
        },
        destructive: {
          DEFAULT: "var(--destructive)",
          foreground: "var(--destructive-foreground)",
        },
        muted: {
          DEFAULT: "var(--muted)",
          foreground: "var(--muted-foreground)",
        },
        accent: {
          DEFAULT: "var(--accent)",
          foreground: "var(--accent-foreground)",
        },
        popover: {
          DEFAULT: "var(--popover)",
          foreground: "var(--popover-foreground)",
        },
        card: {
          DEFAULT: "var(--card)",
          foreground: "var(--card-foreground)",
        },
      },
      fontFamily: {
        sans: ['var(--font-sans)'],
        mono: ['var(--font-mono)'],
      },
      fontSize: {
        xs: 'var(--text-xs)',
        sm: 'var(--text-sm)',
        base: 'var(--text-base)',
        lg: 'var(--text-lg)',
        xl: 'var(--text-xl)',
        '2xl': 'var(--text-2xl)',
        '3xl': 'var(--text-3xl)',
        '4xl': 'var(--text-4xl)',
        '5xl': 'var(--text-5xl)',
        '6xl': 'var(--text-6xl)',
      },
      fontWeight: {
        light: 'var(--font-light)',
        normal: 'var(--font-normal)',
        medium: 'var(--font-medium)',
        semibold: 'var(--font-semibold)',
        bold: 'var(--font-bold)',
      },
      spacing: {
        0: 'var(--space-0)',
        1: 'var(--space-1)',
        2: 'var(--space-2)',
        3: 'var(--space-3)',
        4: 'var(--space-4)',
        5: 'var(--space-5)',
        6: 'var(--space-6)',
        8: 'var(--space-8)',
        10: 'var(--space-10)',
        12: 'var(--space-12)',
        16: 'var(--space-16)',
        20: 'var(--space-20)',
        24: 'var(--space-24)',
      },
      borderRadius: {
        sm: 'var(--radius-sm)',
        DEFAULT: 'var(--radius)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        '2xl': 'var(--radius-2xl)',
        '3xl': 'var(--radius-3xl)',
        full: 'var(--radius-full)',
      },
      boxShadow: {
        sm: 'var(--shadow-sm)',
        DEFAULT: 'var(--shadow)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        xl: 'var(--shadow-xl)',
      },
      transitionDuration: {
        DEFAULT: 'var(--transition-all)',
        colors: 'var(--transition-colors)',
        opacity: 'var(--transition-opacity)',
        shadow: 'var(--transition-shadow)',
        transform: 'var(--transition-transform)',
      },
      zIndex: {
        0: 'var(--z-0)',
        10: 'var(--z-10)',
        20: 'var(--z-20)',
        30: 'var(--z-30)',
        40: 'var(--z-40)',
        50: 'var(--z-50)',
        auto: 'var(--z-auto)',
      },
      keyframes: {
        'fade-up': {
          '0%': { opacity: '0', transform: 'translateY(10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'fade-down': {
          '0%': { opacity: '1', transform: 'translateY(0)' },
          '100%': { opacity: '0', transform: 'translateY(10px)' },
        },
        'scale-fade': {
          '0%': { opacity: '1', transform: 'scale(1)' },
          '100%': { opacity: '0', transform: 'scale(0.95)' },
        },
        'logo-reveal': {
          '0%': { opacity: '0', transform: 'scale(1.1)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        }
      },
      animation: {
        'fade-up': 'fade-up 0.5s ease-out forwards',
        'fade-down': 'fade-down 0.5s ease-out forwards',
        'scale-fade': 'scale-fade 0.5s ease-out forwards',
        'logo-reveal': 'logo-reveal 0.6s ease-out forwards',
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
  safelist: [
    'bg-blue-50',
    'bg-blue-100',
    'bg-green-50',
    'bg-green-100',
    'bg-red-50',
    'bg-red-100',
    'bg-yellow-50',
    'bg-gray-50',
    'bg-gray-100',
    'text-blue-600',
    'text-blue-800',
    'text-green-800',
    'text-red-800',
    'text-gray-900',
    'text-gray-600',
    'text-gray-500',
    'rounded-lg',
    'rounded-md',
    'rounded-full',
    'shadow-sm',
    'shadow-xl',
    'border',
    'border-gray-100',
    'border-gray-200',
    'border-gray-300',
    'p-2',
    'p-4',
    'p-6',
    'p-8',
    'px-3',
    'px-4',
    'px-6',
    'py-2',
    'py-4',
    'py-6',
    'py-8',
    'py-12',
    'py-16',
    'py-24',
    'mt-2',
    'mt-4',
    'mt-6',
    'mt-8',
    'mb-2',
    'mb-4',
    'mb-6',
    'mb-8',
    'mx-auto',
    'my-auto',
    'space-y-2',
    'space-y-4',
    'space-x-4',
    'space-x-8',
    'gap-4',
    'gap-6',
    'gap-8',
    'grid',
    'grid-cols-1',
    'grid-cols-2',
    'grid-cols-3',
    'md:grid-cols-2',
    'flex',
    'flex-col',
    'flex-row',
    'items-center',
    'justify-center',
    'justify-between',
    'w-full',
    'h-full',
    'min-h-screen',
    'max-w-full',
    'max-w-4xl',
    'max-w-7xl',
    'relative',
    'absolute',
    'z-10',
    'z-40',
    'z-50',
    'inset-0',
    'top-0',
    'left-0',
    'right-0',
    'bottom-0',
    'overflow-hidden',
    'text-center',
    'text-sm',
    'text-lg',
    'text-xl',
    'text-3xl',
    'text-4xl',
    'font-medium',
    'font-semibold',
    'font-bold',
    'hidden',
    'md:flex',
    'md:w-1/2',
    'lg:flex',
    'lg:flex-1',
    'lg:justify-end',
    'lg:gap-x-12',
    'lg:hidden',
  ],
} 